1번째 과제 PR
sscc-study/java-racing pull request #15
Opened 2022-07-14 17:32 UTC by k0000k

테스트 코드 작성 완료했습니다.

2022-07-14 23:03 UTC, findstar commented
PR을 요청할 때는 제목을 알맞게 작성해주세요 :)

2022-07-14 23:07 UTC, findstar requested changes
몇가지 코멘트를 남겼으니 확인후 수정 부탁드립니다.

2022-07-14 23:07 UTC, findstar commented on .gitignore
> +!**/src/Stringclass/**
요건 왜 추가하셨을까요? 필요한 내용으로는 보이지 않습니다.

2022-07-14 23:07 UTC, findstar commented on src/main/java/Stringclass.java
> +class Stringclass {
학습테스트에서는 의미없는 클래스는 작성하지 않아도 됩니다.

2022-07-14 23:07 UTC, findstar commented on src/main/java/SetCollection.java
> +
학습테스트에서는 의미없는 클래스는 작성하지 않아도 됩니다.

2022-07-14 23:07 UTC, findstar commented on src/test/java/SetCollectionTest.java
> +import static org.assertj.core.api.Assertions.*;
import 가 흩어져 있고 정리되어 있지 않습니다. 
와일드카드(*) 형태로 import 하기보다는 명시적인 클래스를 import 하도록 개선해주세요

2022-07-14 23:07 UTC, findstar commented on src/test/java/SetCollectionTest.java
> +
공백도 의미가 분명하게 사용해야합니다.

2022-07-14 23:07 UTC, findstar commented on src/test/java/SetCollectionTest.java
> +        assertThat(numbers.contains(1)).isEqualTo(true);
isEqualTo(true); 대신 isTrue()를 사용하면 더 읽기 편해집니다.

2022-07-15 10:19 UTC, k0000k commented
수정 완료했습니다.

2022-07-15 10:21 UTC, findstar commented on .gitignore
> -!**/src/main/**
요건 어떤 내용인가요?

2022-07-15 10:25 UTC, k0000k commented on .gitignore
> -!**/src/main/**
!**/src/main/** 이 부분은 제가 직접 수정한게 아닌데 IDE에서 Git을 사용하는 과정에서 자동으로 추가된 것 같습니다. 그런데 저번 코멘트에서 필요하지 않은 내용이라고 말씀해주셔서 삭제하였습니다!

2022-07-15 10:27 UTC, findstar commented on .gitignore
> -!**/src/main/**
@k0000k 
지난번에는 요런 상태였어요. 파일에 내용이 추가된거죠 그걸 말씀드린거였습니다 :) 
<img width="406" alt="image" src="https://user-images.githubusercontent.com/1266944/179205539-65453ce9-2b0e-450d-9cd2-7323969ada85.png">

2022-07-15 10:44 UTC, k0000k commented on .gitignore
> -!**/src/main/**
아아 확인했습니다! 그러면 .gitignore 파일을 초기 상태로 돌리면 문제 없을까요?

2022-07-15 11:17 UTC, findstar commented on .gitignore
> -!**/src/main/**
@k0000k 넵 원래상태로 되돌리면 됩니다 :)

2022-07-15 13:33 UTC, k0000k commented
.gitignore 파일을 초기 상태로 복구하고, Zoom에서 보여주신 Reformat code 기능 이용해서 코드 정리했습니다.

2022-07-15 13:35 UTC, findstar approved these changes
수고하셨습니다 👍

2022-07-15 13:36 UTC, merged