22/7/15(금) 2회차 과제 PR
sscc-study/java-racing pull request #18
Opened 2022-07-17 01:03 UTC by wygbsr

2022-07-17 01:22 UTC, findstar requested changes

2022-07-17 01:22 UTC, findstar commented on src/main/java/org/sscc/study/Calculator.java
> +    }
Enum 과 BiFunction 을 활용해서 다른 클래스로 분리할 수 있습니다. 
클래스를 분리해서 열학을 나누어 보세요 :)

2022-07-17 01:22 UTC, findstar commented on src/main/java/org/sscc/study/Calculator.java
> +    void bootUp(String input) throws Exception {
함수에 public, private 에 대한 키워드가 누락되어 있네요. 명시적으로 붙여주는 것이 좋습니다.

2022-07-17 01:22 UTC, findstar commented on src/main/java/org/sscc/study/Calculator.java
> +        print();
추상화 레벨이 동일하게 구성되어 있어서 읽기가 좋네요 
잘 하셨습니다. 👍

2022-07-17 01:22 UTC, findstar commented on src/main/java/org/sscc/study/Calculator.java
> +    void print() {
print 보다는 printResult 같은 이름은 어떤가요? 결과를 출력한다는 의미가 더 명확해질 것 같습니다.

2022-07-17 05:32 UTC, wygbsr commented on src/main/java/org/sscc/study/Calculator.java
> +    void bootUp(String input) throws Exception {
처음 작성 시에 Calculator 객체 외부에서 호출되는 bootUp(String)만 default로 선언하고, Calculator 클래스의 필드들과 나머지 메소드는 private으로 선언하였습니다.
그런데 이 경우 테스트 메소드에서 Calculator의 필드 및 메소드에 접근 불가능해서 private도 default 처리하였습니다. 
혹시 필드와 메소드 모두 protected나 public 처리해 주어야하나요?

2022-07-17 05:33 UTC, wygbsr commented on src/main/java/org/sscc/study/Calculator.java
> +        print();
감사합니다. 
슬랙에 소개해 주신 클린 코드 가이드에서 함수가 **한가지 일**만 하도록 권장하고 있는데, 
그렇다면 프로그램을 작성할 때
1) 위와 같이 하나의 head메소드에서 순서대로 다른 메소드(필드 변경, 연산 수행)들을 호출
2) 체인 식으로 클래스 내 메소드가 꼬리물기 호출(1번에서 2번호출, 2번에서 3번호출...)
3) 서브루틴 제외한 모든 메소드를  클래스 외부에서 호출(main등)
중 바람직한 방법이 있나요?

2022-07-17 11:48 UTC, findstar commented on src/main/java/org/sscc/study/Calculator.java
> +    void bootUp(String input) throws Exception {
필드와 메소드 모두 명시적으로 public, private, protected 를 지정해주는 것이 좋습니다. 
default 이기 때문에 접근에 어려움이 있다면 구조를 변경하는 쪽으로 리팩토링 해보는 것이 좋겠습니다.

2022-07-17 11:51 UTC, findstar commented on src/main/java/org/sscc/study/Calculator.java
> +        print();
경우에 따라서 모두 다릅니다. 
메소드 체이닝을 선호하는 경우도 있으나, 
여기서는 흐름을 그대로 나타내는 방식이 제일 무난하다고 생각합니다. 
지금은 1번과 같은 형태가 좋겠습니다.

2022-07-18 04:11 UTC, findstar commented on src/main/java/org/sscc/study/Calculator.java
> +    }
인자가 없는 생성자는 테스트용으로만 사용되는 것 같아요.
테스트에서도 굳이 private 변수를 가지고 있을 필요가 없어보이네요.

2022-07-18 04:11 UTC, findstar commented on src/main/java/org/sscc/study/Calculator.java
> +    public String execute() throws Exception {
메소드와 메소드 사이에는 라인을 하나 비워주세요 :)

2022-07-18 04:11 UTC, findstar commented on src/main/java/org/sscc/study/Calculator.java
> +    private void checkIfNullOrEmpty() throws Exception {
이 메소드는 생성자 에서 처리하는게 어떨까요?

2022-07-18 04:11 UTC, findstar commented on src/main/java/org/sscc/study/Calculator.java
> +        checkInvalidOperator();
마찬가지로 계산할 수 있는지 사전에 검증하는 단계는 생성자에서 처리해도 될것 같아요.

2022-07-18 04:23 UTC, wygbsr commented
커밋에 착오가 있었습니다. 새롭게 커밋할 예정입니다.

2022-07-19 12:38 UTC, findstar approved these changes
피드백 잘 반영해주셨습니다. 
고생하셨어요 👍

2022-07-19 12:38 UTC, merged