1주차 (금) 과제
sscc-study/java-racing pull request #21
Opened 2022-07-17 22:06 UTC by chjih

문자열 사칙 연산 계산기 구현 & 테스트 구현

2022-07-17 22:42 UTC, findstar requested changes

2022-07-17 22:42 UTC, findstar commented on src/main/java/Calculator.java
> +        calculator.run(sc.nextLine());
run 에 입력값을 전달하고, 결과를 별도의 메소드로 반환받는다면
run 대신 Calculator 의 생성자를 활용해보면 어떨까요?

2022-07-17 22:42 UTC, findstar commented on src/main/java/Calculator.java
> +    public int getResult() {
getResult 가 public 일 필요는 없어보입니다.
private 으로 변경해볼 수는 없나요?

2022-07-17 22:42 UTC, findstar commented on src/main/java/Calculator.java
> +    }
Enum 과 BiFunction 을 활용해서 Operator 를 처리하도록
별도의 파일로 분리해보세요.

2022-07-18 11:09 UTC, chjih commented on src/main/java/Calculator.java
> +        calculator.run(sc.nextLine());
calculator 생성자로 입력값을 전달하라는 말씀이신가요?

2022-07-18 11:40 UTC, findstar commented on src/main/java/Calculator.java
> +        calculator.run(sc.nextLine());
@chjih 네 생성자로 전달해도 충분할 것 같아서요

2022-07-19 12:43 UTC, findstar approved these changes
수고하셨습니다. 
다음부터는 코드 컨벤션에 조금 더 신경써주세요. 
익숙하지 않다면, 커밋하기 전에 code reformat 기능을 활용해보세요 :)

2022-07-19 12:43 UTC, merged

2022-07-19 13:51 UTC, chjih commented
커밋전에 Ctrl + Alt + L로 reformat을 했었는데 
혹시 어떤부분이 더 모자른지 알려주실수 있으신가요..?