2번째 과제 PR
sscc-study/java-racing pull request #23
Opened 2022-07-18 09:53 UTC by k0000k

StringCalculator 클래스와 테스트 코드 작성했습니다.

2022-07-18 11:49 UTC, findstar requested changes

2022-07-18 11:49 UTC, findstar commented on src/main/java/StringCalculator.java
> +    }
계산기 로직에서 사용자의 입력값을 받을 필요는 없습니다.
외부의 값을 전달받는 방식으로 변경해보세요

2022-07-18 11:49 UTC, findstar commented on src/main/java/StringCalculator.java
> +    }
Enum 과 BiFunction을 활용해서 별도의 Operator 를 분리할 수 있습니다.

2022-07-18 11:49 UTC, findstar commented on src/main/java/StringCalculator.java
> +    }
main 은 따로 있는게 좋을것 같습니다.

2022-07-22 08:52 UTC, findstar requested changes

2022-07-22 08:52 UTC, findstar commented on src/main/java/StringCalculator.java
> +    public StringCalculator(String InitialInput) {
인자는 소문자로 시작합니다.
`String InitialInput` -> `String initialInput`

마찬가지로 멤버변수도

```
    private final String InitialInput;
    private String[] SplitContents;
```
=> 
```
    private final String initialInput;
    private String[] splitContents;
```

2022-07-22 08:52 UTC, findstar commented on src/main/java/StringInput.java
> +    }
InitialUserInput 이 static 일 필요가 없습니다.
input() 메소드가 수행된 후에 입력값을 반환해도 됩니다.

2022-07-22 08:52 UTC, findstar commented on src/main/java/StringCalculatorMain.java
> +        System.out.println(stringCalculator.getResult());
입력은 별도로 분리했는데 출력은 그대로네요.
간단하게 별도의 출력 메소드를 분리해봐도 좋겠습니다.

2022-07-22 09:34 UTC, k0000k commented on src/main/java/StringCalculatorMain.java
> +        System.out.println(stringCalculator.getResult());
StringOutput과 같은 별도의 클래스를 만들어서 분리하면 되는걸까요??

2022-07-22 09:46 UTC, k0000k commented on src/main/java/StringCalculatorMain.java
> +        System.out.println(stringCalculator.getResult());
별도의 클래스 만들지 않고  stringCalculator 내부에 Output이라는 출력 메소드를 분리해보았습니다!

2022-07-22 09:47 UTC, k0000k commented
3번째 과제인 자동차 경주 1차 작성 커밋이 이번 PR에 함께 들어와버렸는데 괜찮을까요??

2022-07-22 10:48 UTC, findstar requested changes
코드 수정사항 코멘트 남겼습니다.

2022-07-22 10:48 UTC, findstar commented on src/main/java/StringCalculator.java
> +    }
이 메소드는 public 일 필요가 없습니다. 
StringCalculatorMain 클래스에서 호출할 필요 없이
생성자에서 바로 split 처리해도 됩니다.

2022-07-22 10:48 UTC, findstar commented on src/main/java/StringCalculator.java
> +    }
이미 getResult 를 통해서 결과값을 조회할 수 있는데
왜 계산기에서 System.out 출력을 하는 역할을 추가했나요? 
그리고 또 메소드 이름이 대문자로 시작합니다.

2022-07-22 10:48 UTC, findstar commented on src/main/java/StringInput.java
> +    public void Input() {
이런 메소드 이름은 소문자로 시작합니다.

2022-07-23 01:58 UTC, findstar approved these changes
수고하셨습니다. 👍

2022-07-23 01:58 UTC, merged