3차(초간단 자동차경주게임)
sscc-study/java-racing pull request #30
Opened 2022-07-23 18:31 UTC by chjih

랜덤 인터페이스(RandomStrategy)를 코드 내에 어디에 삽입할 지 고민하다가 Cars 클래스 내부에 넣었습니다.
다만, public static으로 선언한 후에 멤버변수에 직접 접근하여 변경해줘야 원하는 테스트코드가 나옵니다..ㅠ
혹시 더 나은 방법이 있을지 궁금합니다!

2022-07-24 05:36 UTC, findstar requested changes

2022-07-24 05:36 UTC, findstar commented on src/main/java/org/sscc/study/racing/RandomStrategy.java
> +    boolean getValue();
getValue 보다는 isMoveAble() 어떤가요? 
이동해야할지 말아야 할지를 알려주는 boolean 값을 반환하는 메소드입니다.

2022-07-24 05:36 UTC, findstar commented on src/main/java/org/sscc/study/racing/Car.java
> +    private String car;
`car` 라기 보다는 `name` 이 더 적당해보이네요.

2022-07-24 05:36 UTC, findstar commented on src/main/java/org/sscc/study/racing/Cars.java
> +    public static RandomStrategy randomStrategy = new Random();
public static 으로 하지 말고, 외부에서 주입받는 방식으로 바꿔보세요

2022-07-24 05:36 UTC, findstar commented on src/main/java/org/sscc/study/racing/Car.java
> +    public void move(RandomStrategy random) {
자동차는 단순히 이동 하도록 하고, 이동할지 말지에 대해서는 상위 클래스가 결정할 수 있습니다.
그렇게 되면 Car 클래스가 RandomStrategy 에 엮이지 않게 됩니다.

2022-07-24 05:36 UTC, findstar commented on src/main/java/org/sscc/study/racing/Cars.java
> +    public List<Car> getResult() {
List<Car>를 그대로 반환하면 일급 컬렉션 객체를 선언한 의미가 줄어듭니다.
결과를 반환하는 다른 방법을 고민해보세요.

2022-07-24 05:36 UTC, findstar commented on src/main/java/org/sscc/study/racing/InputView.java
> +    private static int count;
굳이 static 으로 선언하지 않아도 됩니다.
InputView 도 new 를 통해서 생성한 뒤에 값을 반환해도 됩니다.

2022-07-24 05:36 UTC, findstar commented on src/main/java/org/sscc/study/racing/RandomStrategy.java
> +interface RandomStrategy {
`RandomStrategy` 보다는 `MoveStrategy` 가 더 적당해 보입니다.

2022-07-25 22:44 UTC, chjih commented on src/main/java/org/sscc/study/racing/Cars.java
> +        return new Record(cars);
어제 말씀해주셨던 Record는 그저 또 다른 class 객체로 이해하면 되는건가요?
아니면 혹시 다른 일급 콜렉션 객체처럼 다른 의미가 들어있는건가요?

2022-07-27 12:19 UTC, findstar approved these changes
전체적으로 코드가 이해하기 쉽고 간결해졌습니다. 
몇가지 코멘트 남겼습니다만. 참고로 봐주시고 
다음 과제 진행해주세요 :)

2022-07-27 12:19 UTC, findstar commented on src/main/java/org/sscc/study/racing/AlwaysMove.java
> +public class AlwaysMove implements MoveStrategy {
👍

2022-07-27 12:19 UTC, findstar commented on src/main/java/org/sscc/study/racing/Car.java
> +public class Car {
👍

2022-07-27 12:19 UTC, findstar commented on src/main/java/org/sscc/study/racing/Cars.java
> +        return new Record(cars);
@chjih 결과 값을 담고 있는 객체를 만들어봐도 좋다는 의미였습니다. 
이를 다시 감싼 일급 콜렉션 객체도 만들 수 있겠죠. 
방법은 여러가지가 있을 수 있습니다 :)

2022-07-27 12:19 UTC, findstar commented on src/main/java/org/sscc/study/racing/Controller.java
> +        resultView.printResult(record);
애플리케이션의 전체 흐름이 잘 드러나네요. 👍 
InputView, ResultView 의 추상화 레벨도 같게 되어있습니다. 좋습니다 👍

2022-07-27 12:19 UTC, findstar commented on src/main/java/org/sscc/study/racing/Controller.java
> +        List<Record> record = carRacing.getResult();
굳이 지적하자면 List<Record> 이니까, 변수명은 records 가 맞지 않을까요?

2022-07-27 12:19 UTC, findstar commented on src/main/java/org/sscc/study/racing/RandomMove.java
> +        return random.nextInt(10) >= 4;
이런 기준 값들은 상수화 처리하여 관리하면 좋습니다.

2022-07-27 12:19 UTC, merged